using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Goobstation.FillableForm.UI;

[GenerateTypedNameReferences]
public sealed partial class FillableFormWindow : DefaultWindow
{
    public FillableFormWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
