using System.Linq;
using Content.Shared.Fax;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.Fax.UI;

[GenerateTypedNameReferences]
public sealed partial class FillableFormWindow : DefaultWindow
{
    public FillableFormWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
